### ISSUE TITLE
Missing icons when loading plain kml

### ISSUE THREAD

**Issue by bugfindr** [Raruto/leaflet-kmz#10]
In latest version, facing issue with Icon property in KMZLayer.js file.

![image](https://user-images.githubusercontent.com/6725134/88089125-23dfc300-cba9-11ea-980f-03b6c25bfcbc.png)

![image](https://user-images.githubusercontent.com/6725134/88089275-5ab5d900-cba9-11ea-81cd-f29558dfbaf8.png)

 That's says undefined icon property. Please help on the same.

**Comment by Raruto** [comment]
Hi Bugfindr,
there is probably something wrong with your kmz file (e.g. missing or incorrect [\<Icon\>](https://developers.google.com/kml/documentation/kmlreference#icon) tags).

To debug that you use the following snippet:

```js
var kmz = L.kmzLayer('demo.kmz', {
  geometryToLayer: function(data) {
    console.log(data);
    return L.geoJson(data);
  }
}).addTo(map);
```

Anyway, it would be better if you could also provide an example file ...

_Have a nice day,
Raruto_

**Comment by bugfindr** [comment]
Hi Raruto,
Thank you very much for you quick response.

I just used above code snippet and I don't see above mentioned error today. but still in doubtful.

And major issue now I am facing which is "KMZ style".  Looks like all geometry and icons appearance in default style (blue color). However my KMZ has different color and icon usls and that KMZ working fine with google earth and google Map.

I am attaching a minor KMZ for your test including output  screenshots at my end. 

[demo-test.zip](https://github.com/Raruto/leaflet-kmz/files/4967782/demo-test.zip)

KMZ output on Map.
![image](https://user-images.githubusercontent.com/6725134/88318622-9df28200-cd38-11ea-851b-5d3b484978d8.png)

KMZ Output on Google Earth.
![image](https://user-images.githubusercontent.com/6725134/88318762-da25e280-cd38-11ea-950e-42436dcaaddf.png)

 If you will notice on click popup also not appearing on map. Thank You.

**Comment by Raruto** [comment]
> If I use geometryToLayer then I am facing "KMZ style" issue. Looks like all geometry and icons appearance in default style (blue color). However my KMZ has different color and icons. And that KMZ working fine with google earth and google Map.

That happens because the `geometryToLayer` **option** overrides the following default styling function:

https://github.com/Raruto/leaflet-kmz/blob/ff62f3aa339f896e2e090940153dc84e05aaca75/src/KMZLayer.js#L62

For further details, here you can see a more in-depth example: [leaflet-kmz_gridlayer.html](https://raruto.github.io/leaflet-kmz/examples/leaflet-kmz_gridlayer.html).

> I am attaching a minor KMZ for your test including output screenshots at my end.

Thanks for the demo file, your problem was related to the fact that the file is not actually a "zipped" folder (but a simple "kml" text file).

Take a look at **version 1.0.5** and then let me know if it works.

_Happy testing,
Raruto_

**Comment by bugfindr** [comment]
I just saw leaflet-kmz_gridlayer.html file. but there's no way to apply KMZ/KML direct to map without overrides?

**Comment by Raruto** [comment]
> I just saw [leaflet-kmz_gridlayer.html](https://raruto.github.io/leaflet-kmz/examples/leaflet-kmz_gridlayer.html) file. but there's no way to apply KMZ/KML direct to map without overrides? 

I don't think I understand correctly, however, have you tried (with **version 1.0.5**) to simply do so?

```js
var kmz = L.kmzLayer('demo.kmz').addTo(map);
```

**Comment by bugfindr** [comment]
Test with 1.0.5 and getting error as mentioned below. 

![image](https://user-images.githubusercontent.com/6725134/88340963-5d0b6500-cd5a-11ea-9487-fae38786098a.png)

**Comment by bugfindr** [comment]
@Raruto Never mind. Looks like your change works now. I will back to you If I found something. 

Thank you very much!
