### ISSUE TITLE
Hook into KML parsing method to display GroundOverlay as ImageOverlay

### ISSUE THREAD

**Issue by RockyTV** [Raruto/leaflet-kmz#11]
I know that this library and the underlying lib it uses for converting KML to GeoJSON doesn't support the `GroundOverlay` feature from KML. I'm using this library in a project and I'd like to know if it's possible to execute a custom function before converting the KML to GeoJSON to handle `GroundOverlay` with images.

I have a KMZ file with a KML that has a GroundOverlay with an image in it. My idea was to retrieve this image from the KML and plot it into Leaflet by using Leaflet's `ImageOverlay` layer. 

I know it's possible to hook into `geometryToLayer`, but is it possible to hook into the KML parsing function?

**Comment by Raruto** [comment]
Hi Alexandre,

> is it possible to hook into the KML parsing function?

take a look at the `xml` paremeter added in **version 1.0.5**:

https://github.com/Raruto/leaflet-kmz/blob/dd56ed30b1563c25ac10fa357762d28ba8ddf206/src/KMZLayer.js#L63

I'm not sure this could be the definitive solution (so be careful), but let me know if you have better ideas.

> My idea was to retrieve this image from the KML and plot it into Leaflet by using Leaflet's `ImageOverlay` layer.

If you succeed, then could you kindly share a working example / demo? (to be added among the other examples of this library...)

_Happy coding,
Raruto_

**Comment by RockyTV** [comment]
Thanks for the reply!

I managed to get the parsed XML, but now I have a problem: how do I access the file contents of the KMZ file so I can upload the image as a blob and display it in Leaflet?

**Comment by Raruto** [comment]
Hi Alexandre,
could you provide a demo? (talking in words makes things a little more difficult...)

_Raruto_

**Comment by Raruto** [comment]
For anyone interested, here is an example code to support additional tags:

```js
// Instantiate KMZ layer (async)
var kmz = L.kmzLayer(null, {
  geometryToLayer: function(data, xml) {
   // parse supported GeoJSON features
    let layer = this._geometryToLayer(data, xml);
   // include unsupported GroundOverlays
    let el = xml.getElementsByTagName('GroundOverlay');
    for (let k = 0; k < el.length; k++) {
      l = _.parseGroundOverlay(el[k], data.properties); // blob images are within the "data.properties.icons"
      if (l) {
        layer.addLayer(l);
      }
    }
    return layer;
  }
});
```

Anyway, **version 1.0.6** should now start taking care of this.

**Comment by RockyTV** [comment]
Hey, sorry for the time it took to reply. I forgot to post my code in here. Here's what I did:

```tsx
    kmzLayer = new KMZLayer(kmzUrl, {
    ballon: false,
    preferCanvas: true,
    geometryToLayer: (data: any, xml: XMLDocument) => {
        if (!data.features.length) {
            const groundOverlays = xml.getElementsByTagName('GroundOverlay');
            let imgHref: string | null = '';
            let latLon: [number, number, number, number] = [0, 0, 0, 0];

            if (groundOverlays.length) {
                const groundOverlay = groundOverlays[0];
                const imgGroundOverlay = groundOverlay.getElementsByTagName('Icon')[0];
                const latLonBox = groundOverlay.getElementsByTagName('LatLonBox')[0];

                latLon = [+latLonBox.getElementsByTagName('north')[0].textContent!, +latLonBox.getElementsByTagName('south')[0].textContent!, +latLonBox.getElementsByTagName('east')[0].textContent!, +latLonBox.getElementsByTagName('west')[0].textContent!];

                imgHref = imgGroundOverlay.getElementsByTagName('href')[0].textContent!.trim();
            }

            fetch(kmzUrl).then((response) => {
                if (response.status === 200 || response.status === 0) {
                    return Promise.resolve(response.blob());
                }
                return Promise.reject(new Error(response.statusText));
            }).then(JSZip.loadAsync).then((zip) => zip.file(imgHref!)?.async('blob'))
                .then((imgData) => {
                    let urlImgBlob = URL.createObjectURL(imgData);

                    kmzLayer = L.imageOverlay(urlImgBlob, [[latLon[0], latLon[2]], [latLon[1], latLon[3]]], { interactive: true });
                    kmzLayer.addTo(mapRef.current!.leafletElement);

                }, (err) => {
                    console.log('Error fetching image from KMZ ground overlay: ', err);
                });
        }


        return L.geoJSON(data);
    },
});
```

It's not compilable because it requires other parts of my custom component and I'm not sure if I'm allowed to share the entire source code of the component, but since I wrote the part that loads `GroundOverlay` as `ImageOverlay`. I decided to share it. The underlying component is a component that allows the user to upload a KMZ file and preview it before inserting it into a map. Basically what I've done is check if the GeoJSON layer is null, then try to parse the XML. When it finds a `GroundOverlay` tag it then extracts the coordinates from it. Then it fetches the KMZ file blob URL and opens it with JSZip to retrieve the image and store it as a blob, and then plot an `ImageOverlay` with the retrieved coordinates so the user can preview how the KMZ looks like after it's added to the map. 

It's not included here but after the user clicks a button the image blob is sent to the backend so it can be uploaded to storage and the URL is saved in the database for future use.
