### ISSUE TITLE
Fit kmz layer bounds on leaflet map

### ISSUE THREAD

**Issue by bugfindr** [Raruto/leaflet-kmz#12]
@Raruto Would like to know. Is there any option to get focused on appeared KML? Thanks!

**Comment by Raruto** [comment]
Hi bugfindr,
I don't think I understand, could you be clearer about your intentions?

_Thanks,
Raruto_

**Comment by bugfindr** [comment]
A option to maintain map center and bound area on KML Layer geometry. 

Like In Google Map, we do have that option named "**preserveViewport**" for KML Layers object.

Please check screenshot:

![image](https://user-images.githubusercontent.com/6725134/90022495-3c3a8d80-dcd0-11ea-9ecc-80555198bd5f.png)

Thanks!

**Comment by Raruto** [comment]
As you can see from the image above you should also add the "map" option to perform that action.

To achieve a similar result you can try to do as follows:

```js
var kmz = L.kmzLayer().addTo(map);

kmz.on('load', function(e) {
  map.fitBounds(kmz.getBounds());
  // OR map.flyToBounds(kmz.getBounds());
  // OR map.panInsideBounds(kmz.getBounds())
});

kmz.load('demo.kmz');
```

**More info at:**
- [Leaflet Map methods for modifying map state](https://leafletjs.com/reference-1.6.0.html#map-methods-for-modifying-map-state)
- [Leaflet FeatureGroup](https://leafletjs.com/reference-1.6.0.html#featuregroup)

**Comment by bugfindr** [comment]
@Raruto That's works. Thank you very much.
