### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by JORGEMAL** [Raruto/leaflet-kmz#14]
Hi,

Can you provide a tip to enable CORS in order to use the files in your example (https://raruto.github.io/leaflet-kmz/examples/regions.kmz)?

I suppose that CORS must be enabled somewhere within your JavaScript code. Am I correct?
(Somewhere between <script> and </script>)

Regards,
Jorge Maldonado

**Comment by Raruto** [comment]
Hi Jorge,
you can try replacing these lines:

```js
kmz.load('https://raruto.github.io/leaflet-kmz/examples/regions.kmz');
kmz.load('https://raruto.github.io/leaflet-kmz/examples/capitals.kmz');
kmz.load('https://raruto.github.io/leaflet-kmz/examples/globe.kmz');
kmz.load('https://raruto.github.io/leaflet-kmz/examples/etna.kmz');
```

with the following:

```js
kmz.load('https://cors-anywhere.herokuapp.com/https://raruto.github.io/leaflet-kmz/examples/regions.kmz');
kmz.load('https://cors-anywhere.herokuapp.com/https://raruto.github.io/leaflet-kmz/examples/capitals.kmz');
kmz.load('https://cors-anywhere.herokuapp.com/https://raruto.github.io/leaflet-kmz/examples/globe.kmz');
kmz.load('https://cors-anywhere.herokuapp.com/https://raruto.github.io/leaflet-kmz/examples/etna.kmz');
```

If in trouble, try searching on [stackoverflow.com](https://stackoverflow.com/search?q=cors+github+pages)

_Have a nice day,
Raruto_
