### ISSUE TITLE
Package not being recognized 

### ISSUE THREAD

**Issue by Vincentqchen** [Raruto/leaflet-kmz#27]
Hey, 

I've just used yarn to install this package for react leaflet 3.2.0 and leaflet 1.6.0 and for some reason, the new package isn't being recognized. I tried using L.kmzLayer but get this error `leaflet__WEBPACK_IMPORTED_MODULE_4___default.a.kmzLayer is not a function`. Is this package not combatable with my versions?

**Comment by Raruto** [comment]
Hi Vincent,
sorry I can't help you because I don't use react leaflet, but if I'm not mistaken somewhere on the net there should be a fork of a user that should be compatible with that library.

_Have a nice day,
Raruto_
