### ISSUE TITLE
hotSpot not supported

### ISSUE THREAD

**Issue by frashpikass** [Raruto/leaflet-kmz#38]
Hello!
The problem I'm facing with is that whenever a KMZ is loaded, marker icons will always be placed centered on their center. For example, look at how this icon is rendered on the Leaflet map:

![image](https://github.com/Raruto/leaflet-kmz/assets/2952445/c85668d7-6725-443b-b6f7-c43f63a11600)

This is how it looks on Google Earth:

![image](https://github.com/Raruto/leaflet-kmz/assets/2952445/3cc0077f-74e4-4c01-b8e6-936c9dfd3f78)

As you can see, the narrow tip of the teardrop should centered on the road. This is how the icon is styled in the kml:

```xml
<Style id="icon-1899-097138-labelson-nodesc">

  <IconStyle>
    <Icon>
      <href>files/icon-4.png</href>
    </Icon>
    <hotSpot x="32" y="64" xunits="pixels" yunits="insetPixels"/>
  </IconStyle>

  <BalloonStyle>
    <text><![CDATA[<h3>$[name]</h3>]]></text>
  </BalloonStyle>

</Style>
```

I'm using Leaflet KMZ v1.0.9 and Leaflet v1.9.4.

**Comment by Raruto** [comment]
Hi Frash,

the [\<hotSpot\>](https://developers.google.com/kml/documentation/kmlreference#iconstyle) and [\<BalloonStyle\>](https://github.com/Raruto/leaflet-kmz/issues/13) tags are currently not supported.

Within old issues you can find described an alternative solution that you can try to implement it by yourself:

https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/src/KMZLayer.js#L55

https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/src/KMZLayer.js#L60-L138

**For more info:**

- https://github.com/Raruto/leaflet-kmz/issues?q=geometrytolayer

👋 Raruto
