### ISSUE TITLE
Possible to pass in data directly rather than through a url ?

### ISSUE THREAD

**Issue by dceejay** [Raruto/leaflet-kmz#39]
Is it possible to pass data in directly (a KMZ as a buffer) rather than have to call `.add(url)` ?

**Comment by Raruto** [comment]
Hi Dave,

did you miss your previous issue? 👉  https://github.com/Raruto/leaflet-kmz/issues/18

If in doubts, also check the closed PR / issues, eg: https://github.com/Raruto/leaflet-kmz/pull/29

👋 Raruto

**Comment by dceejay** [comment]
Hi yeah - I still fail with those... I always get an "Unhandled Promise Rejection error from window.JSZip.loadAsync

```
"Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.JSZip.loadAsync')"
```

 - so I guess I'm not calling it right somehow.

I'm just calling `kmz.parse(arr, { name: "myMKZ", icons: {} });`

where `arr` is an [Arraybuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) of the kmz file.

**Comment by Raruto** [comment]
Try preventing dependency lazy loading, as previously explained in: https://github.com/Raruto/leaflet-kmz/issues/16#issuecomment-678701526

Just to be sure, are you in a browser context? (ie. global `window` variable is defined?)

👋 Raruto

**Comment by dceejay** [comment]
Hi,,
finally that was it - I was missing the include of the jszip library... All good now
Many thanks
