### ISSUE TITLE
Leaflet FileLayer integration

### ISSUE THREAD

**Issue by aliencraft1512** [Raruto/leaflet-kmz#4]
Great plugin!!! it would be even better  if you collaborate with the developer of leaflet filelayer  to create an integrated solution.

**Comment by Raruto** [comment]
Thanks for your message,
but maybe you should directly ask to @leplatrem if he might be interested in adding this to his plugin...

**Comment by leplatrem** [comment]
Unfortunately I don't really maintain Leaflet.FileLayer anymore, since I left the company where we were using it...

**Comment by Raruto** [comment]
Ok, thanks for the info.
Now let's see if it matters to someone else [#72](https://github.com/makinacorpus/Leaflet.FileLayer/issues/72)
