### ISSUE TITLE
Prevent auto loading KMZ layers on map until user clicks on related L.Control.Layer checkbox

### ISSUE THREAD

**Issue by kg6uyz** [Raruto/leaflet-kmz#41]
Is there a way to load the list of KMZ's but not auto load the KMZ's onto the map until a user clicks one of the check mark boxes?

**Comment by Raruto** [comment]
`L.Control.Layers` follows the state of the level:

https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/examples/leaflet-kmz.html#L50

1. You can remove them individually as soon as they are loaded (eg. `e.layer.remove()`):

https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/examples/leaflet-kmz.html#L52-L55

2. or, simply avoid adding the parent layer to the map (ie. `kmz.addTo(map)`):

https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/examples/leaflet-kmz.html#L50

**Comment by kg6uyz** [comment]
So, basically it appears like its a no?   e.layer.remove removes all layer selections from the map after they are loaded up which wont do, its a cool feature though.  The KMZ's have to be loaded before the list populates as a selectable option to remove/add the layer from view.

**Comment by Raruto** [comment]
> So, basically it appears like its a no?

I think I have proven the opposite.

After that, it is up to you use/edit the code according to your needs.

👋 Raruto
