### ISSUE TITLE
Vue.js component

### ISSUE THREAD

**Issue by zeeuss** [Raruto/leaflet-kmz#6]
Hi,

Please tell me how can I use this library on vuejs ([vue2leaflet](https://github.com/vue-leaflet/Vue2Leaflet)) project?

Thank you!

**Comment by Raruto** [comment]
I don't use vuejs, but according to their [documentation](https://korigan.github.io/Vue2Leaflet/#/faq/?id=how-create-plugin), I think you will have to develop a dedicated plugin.

Let me know if you need a hand in "understanding" this plugin...

**Comment by zeeuss** [comment]
Thanks @Raruto for answer!
I have successfully included the library.  I fixed some errors, but the following error remained:

RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer chunk-vendors.js line 13300 > eval:287:11
    _isZipped KMZLoader.js:285
    _parse KMZLoader.js:44
    _load KMZLoader.js:39
    <анонимный> self-hosted:1021
    onreadystatechange KMZLoader.js:338

How we solve it?

**Comment by Raruto** [comment]
It could be that your kmz file is not correctly loaded by the browser, are you sure that there are no other warnings before this fatal error?

**Comment by zeeuss** [comment]
Mozilla: no
Chrome:
![Capture](https://user-images.githubusercontent.com/34582382/69789260-e1581900-11c8-11ea-96e7-b99aabaca206.PNG)
![Capture2](https://user-images.githubusercontent.com/34582382/69789397-24b28780-11c9-11ea-87e5-b94367cbbfff.PNG)

**Comment by Raruto** [comment]
There is a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error related to the file: **[capitals.kmz](https://raruto.github.io/examples/leaflet-kmz/capitals.kmz)**. Try loading this file directly from your server to solve.

**Comment by zeeuss** [comment]
I loaded the file directly from my server. See the following errors below:
Chrome:
![Chrome](https://user-images.githubusercontent.com/34582382/69813346-af5faa80-11fa-11ea-9d61-ff4b9cde6107.PNG)

Mozilla:
![Mozilla](https://user-images.githubusercontent.com/34582382/69813369-b7b7e580-11fa-11ea-9085-412f523dd91d.PNG)

**Comment by Raruto** [comment]
From what I see it looks like you are trying to open it directly from the file manager.
If you are testing on a localhost server you must access the html page in a similar way to the following: http://localhost/my-example-file.html

**PS** (as already recommended [here](https://github.com/vue-leaflet/Vue2Leaflet/issues/477)) if you also provide **code samples**, we may also better understand how to help you.

**Comment by zeeuss** [comment]
this is my code:

<template>
    <div id="app" style="height: 100%; width: 100%">
        <div>
        <l-map
                style="height: 100%; width: 100%; position: absolute;"
                :zoom="zoom"
                :center="center"
                @update:zoom="zoomUpdated"
                @update:center="centerUpdated"
                @update:bounds="boundsUpdated"
                :options="{ zoomControl: false}"
                ref="myMap"
        >
            <l-tile-layer :url="url"></l-tile-layer>
        </l-map>
    </div>
    </div>
</template>

<script>
import { KMZParser }  from 'leaflet-kmz'
import L from 'leaflet'
import kmz from '../kmzFiles/regions.kmz'

export default {
data () {
	url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png'
     },
      mounted () {
            this.$nextTick(() => {
                const map = this.$refs.myMap.mapObject
                const control = L.control.layers(null, null, { collapsed:false }).addTo(map);
                const kmzParser = new KMZParser({
                    onKMZLoaded: function(layer, name) {
                        control.addOverlay(layer, name);
                        layer.addTo(map);
                           }
                        });
                kmzParser.load(kmz)
               
            })
        }
}
<script>

**Comment by Raruto** [comment]
I think you need to change this lines:
```js
// REMOVE: import kmz from '../kmzFiles/regions.kmz'

kmzParser.load('../kmzFiles/regions.kmz') 
```

**Comment by DonNicoJs** [comment]
Sorry to hijack the issue :) @Raruto Would you be interested to write a plugin / collaborate on one? I mean for vue-leaflet if so I can add you to the org!

**Comment by Raruto** [comment]
Hi @DonNicoJs,

I don't usually use these types of frameworks, but let me know if you need some tips if you are planning to develop a wrapper plugin.
