### ISSUE TITLE
How to remove Fill Color

### ISSUE THREAD

**Issue by bug-asanka** [Raruto/leaflet-kmz#8]
Sir

This plugin is great.

I can not do followings.

1.    Can not remove polygon autofill
2.    check boxes are loaded as checked.

**Comment by Raruto** [comment]
> 1. Can not remove polygon autofill

Maybe there are other ways to achieve this, have you tried doing so?
https://developers.google.com/kml/documentation/kmlreference#color

> 2. check boxes are loaded as checked.

I think you are referring to the following piece of code:

```js
// Instantiate KMZ parser (async)
var kmzParser = new L.KMZParser({
  onKMZLoaded: function(layer, name) {
    control.addOverlay(layer, name);
    // layer.addTo(map); <-- you can try by removing this line.
  }
});
```
